export enum Category {
  MODULE_00 = 'Introductions & Course Map',
  MODULE_1 = 'Architecting Fundamentals',
  MODULE_2 = 'Account Security',
  MODULE_3 = 'Networking, Part 1',
  MODULE_4 = 'Compute',
  MODULE_5 = 'Storage',
  MODULE_6 = 'Database Services',
  MODULE_7 = 'Monitoring and Scaling',
  MODULE_8 = 'Automation',
  MODULE_9 = 'Containers (and Microservices)',
  MODULE_10 = 'Networking, Part 2',
  MODULE_11 = 'Serverless Architecture',
  MODULE_12 = 'Edge Services',
  MODULE_13 = 'Backup and Recovery',
}
